channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=24.0
- pip:
  - mlflow==3.8.0
  - cloudpickle==3.1.2
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.5.2
  - scipy==1.13.0
name: mlflow-env
